// app/(root)/layout.js

export const metadata = {
  title: "Clicon - ECommerce FullStack",
  description: "Generated by create next app",
};

export default function WebLayout({ children }) {
  return <main>{children}</main>;
}
